### ISSUE TITLE
Alternative to Play Store

### ISSUE THREAD

**Issue by GenericMale** [rudoyeugene/pdnss#1]
Love this little App!

Just one minor request:
Could you maybe upload Release APKs on Github or set this Project up on F-Droid?
Publishing a Release on Github is incredibly easy by using Github Actions and can be fully automated.

Some people try to avoid using the Play Store because of privacy concerns.

Thanks!!

**Comment by rudoyeugene** [comment]
Done, now each time I do push of the App you'll get an apk that you can use on your own, without Play Store

**Comment by IzzySoft** [comment]
Would be great if that were a release build, signed with a release key (currently, it's a debug build with a debug key) – especially as this is about a sensitive task 😉 That said, are there some screenshots, and maybe some description? Maybe we can add pdnss to the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid) then.
